name: python-packages

# Run on push on main branch
on:
  push:
    branches: [ main ]
    
jobs:
  # Job to run pigar to generate requirements.txt from python files or notebooks
  generate-requirements:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
     
      - name: Install pigar
        run: |
          python -m pip install --upgrade pip
          pip install pigar
      
      # Use pigar. See options https://github.com/damnever/pigar 
      - name: Generate requirements with pigar
        run: |
          pigar
          
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 🤖 Generate requirements for python 3.7
          commit_user_name: Requirements Bot
